### ISSUE TITLE
how many lineages in P.2?

### ISSUE THREAD

**Issue by liamxg** [MDU-PHL/pango-collapse#11]
Dear @Wytamma,
Could you please tell me each VOC, VOI and VUM include how many lineages?

**Comment by Wytamma** [comment]
P.2 only has P.2
<img width="834" alt="image" src="https://github.com/MDU-PHL/pango-collapse/assets/13726005/3aa4bf80-5412-4f33-94c4-5eaa771043b9">

**Comment by liamxg** [comment]
Dear @Wytamma,

P.2 means "B.1.1.28.1"?

**Comment by Wytamma** [comment]
Hi @liamxg,

I just update the code for the [pango-watch ](https://github.com/MDU-PHL/pango-watch) tree file above -> https://raw.githubusercontent.com/MDU-PHL/pango-watch/main/tree/data.json

Each node has a `num_children` field that counts the total number of child lineages for that lineage. 

Kind reagds,

Wytamma

**Comment by liamxg** [comment]
Dear @Wytamma,
thanks.

how to view the data.json file, any tools?

<img width="1381" alt="image" src="https://github.com/MDU-PHL/pango-collapse/assets/46078579/0c538997-cd41-43a8-be63-cd0296317b3d">

**Comment by liamxg** [comment]
when i search CH.1.1 from GISAID, it reports:

<img width="1206" alt="image" src="https://github.com/MDU-PHL/pango-collapse/assets/46078579/84162263-6aff-487c-983b-c16d80510d30">
is this normal?

**Comment by Wytamma** [comment]
It’s just a JSON file so you should be able to read it in any programming language :D 

DV and FK are both sub lineages of CH.1.1

**Comment by liamxg** [comment]
Dear @Wytamma,
Thank you, how could I input it into R, and show it, any tips, I never use json to show data, thanks.
