### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by liamxg** [MDU-PHL/pango-collapse#9]
Dear @Wytamma, I have install issue:

(base) simon@192 MDU-PHL % pip install pango-collapse
Collecting pango-collapse
  Using cached pango_collapse-0.7.1-py3-none-any.whl (19 kB)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /Users/simon/opt/miniconda3/lib/python3.9/site-packages (from pango-collapse) (1.25.2)
Requirement already satisfied: pandas<=1.5.3,>=1.3 in /Users/simon/opt/miniconda3/lib/python3.9/site-packages (from pango-collapse) (1.5.3)
Collecting pango-aliasor<0.4.0,>=0.3.0 (from pango-collapse)
  Using cached pango_aliasor-0.3.0-py3-none-any.whl (4.1 kB)
Collecting typer[all]<0.7.0,>=0.6.1 (from pango-collapse)
  Using cached typer-0.6.1-py3-none-any.whl (38 kB)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/Users/simon/opt/miniconda3/lib/python3.9/site-packages/numpy-1.25.2.dist-info/METADATA'

**Comment by Wytamma** [comment]
Solved

**Comment by liamxg** [comment]
Dear @Wytamma,
thanks.
